using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Timers;

namespace problemaTimer
{
    class eserciziotimer
    { //system class instanciated
        public static Timer Time = new Timer();

        public static int min; //var minutes 
        public static int count = 1; //index per line 

        /// <summary>
        /// entry point 
        /// </summary>
        /// <param ></param>
        static void Main()
        {
            Console.WriteLine("Add the number of minutes: \n");
            min = int.Parse(Console.ReadLine()); //var with minutes input 
            Console.WriteLine("You really want to wait {0} minute(s)? Answer Yes/No", min);
            var a = Console.ReadLine();
            if (a == "yes")
            {
                Console.WriteLine("Ok, then...Wait...");
                Time.Interval = 1000; //distance between the appearence of the lines 

                //calling event 
                Time.Elapsed += Tmr_Elapsed;
                //start of the event
                Time.Start();
            }
            else if (a == "no")
            {
                Console.WriteLine("See you next time...\n Press a key to exit...");
            }
            Console.ReadKey();
        }
        /// <summary>
        /// efunction generated by the event 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private static void Tmr_Elapsed(object sender, ElapsedEventArgs e)
        {

            Console.Write("Allarme!!  \n{0}. {1}  you just wasted a minute of your life, congratulations!! \r", count++, DateTime.Now); //in each line write the datetime and the counting of minutes

            if (count > min) //in the counting in the lines are greater than the input the usr gave stop the program 
            {
                Time.Stop(); //event stop

                Console.WriteLine("\n Halleluhja!"); //alert with the finished cycle
                Console.WriteLine("You are still here? Press a key to exit..."); //written command to exit the program at the end of the event
            }

        }
    }
    /// <summary>
    /// class with alarm event and properties of an alarm 
    /// </summary>
    public static class sveglia 
    { 
        /// <summary>
        /// properties related to the physical object alarm 
        /// </summary>
        static public int minutes { get; set; }
        static public int hours { get; set; }
        static public int seconds { get; set; }
        static public string sound { get; set; }
        static public string color { get; set; }
        static public string shape { get; set; }
        static public int volume { get; set; }
        static public string ringbells { get; set; }

        //event related to the object 
        static public event Action alarm;
        
        

    }
}
